[2025-04-08 13:29:22 +0530] [15937] [INFO] Starting gunicorn 20.1.0
[2025-04-08 13:29:22 +0530] [15937] [INFO] Listening at: http://0.0.0.0:5000 (15937)
[2025-04-08 13:29:22 +0530] [15937] [INFO] Using worker: sync
[2025-04-08 13:29:22 +0530] [15939] [INFO] Booting worker with pid: 15939
[2025-04-08 13:31:06,276] ERROR in app: Exception on /admin/logger [GET]
Traceback (most recent call last):
  File "/home/ashu/.local/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.local/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.local/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.local/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/Desktop/portfolio-v3/app_sqlite.py", line 261, in wrapped_view
    return view(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/ashu/Desktop/portfolio-v3/app_sqlite.py", line 1184, in admin_logger
    return render_template('admin/logger.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.local/lib/python3.12/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.local/lib/python3.12/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/ashu/.local/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ashu/Desktop/portfolio-v3/templates/admin/logger.html", line 1, in top-level template code
    {% extends "admin/base.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.local/lib/python3.12/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ashu/.local/lib/python3.12/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: admin/base.html
[2025-04-08 13:32:25 +0530] [17136] [INFO] Starting gunicorn 20.1.0
[2025-04-08 13:32:29 +0530] [15937] [INFO] Handling signal: int
[2025-04-08 13:32:29 +0530] [15939] [INFO] Worker exiting (pid: 15939)
[2025-04-08 13:32:29 +0530] [15937] [INFO] Shutting down: Master
[2025-04-08 13:32:33 +0530] [17223] [INFO] Starting gunicorn 20.1.0
[2025-04-08 13:32:33 +0530] [17223] [INFO] Listening at: http://0.0.0.0:5000 (17223)
[2025-04-08 13:32:33 +0530] [17223] [INFO] Using worker: sync
[2025-04-08 13:32:33 +0530] [17224] [INFO] Booting worker with pid: 17224
[2025-04-08 13:33:13 +0530] [17224] [INFO] Worker exiting (pid: 17224)
[2025-04-08 13:33:13 +0530] [17223] [INFO] Handling signal: term
[2025-04-08 13:33:13 +0530] [17223] [INFO] Shutting down: Master
[2025-04-08 13:35:47 +0530] [18302] [INFO] Starting gunicorn 20.1.0
[2025-04-08 13:35:47 +0530] [18302] [INFO] Listening at: http://0.0.0.0:5000 (18302)
[2025-04-08 13:35:47 +0530] [18302] [INFO] Using worker: sync
[2025-04-08 13:35:47 +0530] [18303] [INFO] Booting worker with pid: 18303
[2025-04-08 13:35:47 +0530] [18303] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1319, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app_sqlite.py'; 'app_sqlite' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 388, in import_app
    raise ImportError(msg % (module.rsplit(".", 1)[0], obj))
ImportError: Failed to find application, did you mean 'app_sqlite:app'?
[2025-04-08 13:35:47 +0530] [18303] [INFO] Worker exiting (pid: 18303)
[2025-04-08 13:35:47 +0530] [18302] [INFO] Shutting down: Master
[2025-04-08 13:35:47 +0530] [18302] [INFO] Reason: Worker failed to boot.
[2025-04-08 13:36:46 +0530] [19022] [INFO] Starting gunicorn 20.1.0
[2025-04-08 13:36:46 +0530] [19022] [INFO] Listening at: http://0.0.0.0:5000 (19022)
[2025-04-08 13:36:46 +0530] [19022] [INFO] Using worker: sync
[2025-04-08 13:36:46 +0530] [19077] [INFO] Booting worker with pid: 19077
[2025-04-08 13:36:47 +0530] [19022] [INFO] Handling signal: winch
[2025-04-08 13:38:03 +0530] [19022] [INFO] Handling signal: hup
[2025-04-08 13:38:03 +0530] [19022] [INFO] Hang up: Master
[2025-04-08 13:38:03 +0530] [19022] [WARNING] Worker with pid 19077 was terminated due to signal 1
[2025-04-08 13:38:03 +0530] [19680] [INFO] Booting worker with pid: 19680
[2025-04-08 13:39:51 +0530] [19680] [INFO] Worker exiting (pid: 19680)
[2025-04-08 13:39:51 +0530] [19022] [INFO] Handling signal: term
[2025-04-08 13:39:51 +0530] [19022] [INFO] Shutting down: Master
[2025-04-08 13:39:51 +0530] [20142] [INFO] Starting gunicorn 20.1.0
[2025-04-08 13:39:51 +0530] [20142] [INFO] Listening at: http://0.0.0.0:5000 (20142)
[2025-04-08 13:39:51 +0530] [20142] [INFO] Using worker: sync
[2025-04-08 13:39:51 +0530] [20143] [INFO] Booting worker with pid: 20143
[2025-04-08 13:39:58,046] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:23,279] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:29,263] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:29,621] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:29,952] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:30,238] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:30,431] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:30,626] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:30,817] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:31,032] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:40:31,126] INFO in app_sqlite: Viewing app.log logs
[2025-04-08 13:41:22 +0530] [20142] [INFO] Handling signal: winch
[2025-04-08 13:41:38 +0530] [20142] [INFO] Handling signal: winch
[2025-04-08 13:41:40 +0530] [20142] [INFO] Handling signal: hup
[2025-04-08 13:41:40 +0530] [20142] [INFO] Hang up: Master
[2025-04-08 13:41:40 +0530] [20142] [WARNING] Worker with pid 20143 was terminated due to signal 1
[2025-04-08 13:41:40 +0530] [20689] [INFO] Booting worker with pid: 20689
[2025-04-08 13:42:37 +0530] [20689] [INFO] Worker exiting (pid: 20689)
[2025-04-08 13:42:37 +0530] [20142] [INFO] Handling signal: term
[2025-04-08 13:42:37 +0530] [20142] [INFO] Shutting down: Master
[2025-04-08 13:42:37 +0530] [20919] [INFO] Starting gunicorn 20.1.0
[2025-04-08 13:42:37 +0530] [20919] [INFO] Listening at: http://0.0.0.0:5000 (20919)
[2025-04-08 13:42:37 +0530] [20919] [INFO] Using worker: sync
[2025-04-08 13:42:37 +0530] [20920] [INFO] Booting worker with pid: 20920
[2025-04-08 13:47:27 +0530] [20919] [INFO] Handling signal: int
[2025-04-08 13:47:27 +0530] [20920] [INFO] Worker exiting (pid: 20920)
[2025-04-08 13:47:27 +0530] [20919] [INFO] Shutting down: Master
[2025-04-08 13:47:40 +0530] [22094] [INFO] Starting gunicorn 20.1.0
[2025-04-08 13:47:40 +0530] [22094] [INFO] Listening at: http://0.0.0.0:5000 (22094)
[2025-04-08 13:47:40 +0530] [22094] [INFO] Using worker: sync
[2025-04-08 13:47:40 +0530] [22095] [INFO] Booting worker with pid: 22095
[2025-04-08 13:47:40 +0530] [22095] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1319, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app_sqlite.py'; 'app_sqlite' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 388, in import_app
    raise ImportError(msg % (module.rsplit(".", 1)[0], obj))
ImportError: Failed to find application, did you mean 'app_sqlite:app'?
[2025-04-08 13:47:40 +0530] [22095] [INFO] Worker exiting (pid: 22095)
[2025-04-08 13:47:40 +0530] [22094] [INFO] Shutting down: Master
[2025-04-08 13:47:40 +0530] [22094] [INFO] Reason: Worker failed to boot.
[2025-04-08 13:48:11 +0530] [22277] [INFO] Starting gunicorn 20.1.0
[2025-04-08 13:48:11 +0530] [22277] [INFO] Listening at: http://0.0.0.0:5000 (22277)
[2025-04-08 13:48:11 +0530] [22277] [INFO] Using worker: sync
[2025-04-08 13:48:11 +0530] [22278] [INFO] Booting worker with pid: 22278
[2025-04-08 13:48:11 +0530] [22277] [INFO] Handling signal: winch
[2025-04-08 13:48:54 +0530] [22277] [INFO] Handling signal: winch
[2025-04-08 13:53:07 +0530] [22277] [INFO] Handling signal: int
[2025-04-08 13:53:07 +0530] [22278] [INFO] Worker exiting (pid: 22278)
[2025-04-08 13:53:07 +0530] [22277] [INFO] Shutting down: Master
